export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGE: "ADD_MESSAGE",
  IS_ONLINE: "IS_ONLINE",
  SET_MESSAGES_SEARCH: "SET_MESSAGES_SEARCH",
  SET_USER_CONTACTS: "SET_USER_CONTACTS",
  SET_ONLINE_USERS: "SET_ONLINE_USERS",
  SET_FILTERED_CONTACTS: "SET_FILTERED_CONTACTS",
  SET_VIDEO_CALL: "SET_VIDEO_CALL",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  END_CALL: "END_CALL",
  SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",
  SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
  SET_EXIT_CHAT: "SET_EXIT_CHAT",
};

export const SocketCases = {
  ADD_USER: "add-user",
  ONLINE_USERS: "OnlineUsers",
  SEND_MSG: "send-msg",
  MSG_RECEIVE: "msg-receive",

  OUTGOING_VOICE_CALL: "outgoing-voice-call",
  INCOMING_VOICE_CALL: "incoming-voice-call",

  OUTGOING_VIDEO_CALL: "outgoing-video-call",
  INCOMING_VIDEO_CALL: "incoming-video-call",

  REJECT_CALL: "reject-call",
  CALL_REJECTED: "call-rejected",

  ACCEPT_INCOMING_CALL: "accept-incoming-call",
  CALL_ACCEPTED: "call-accepted",

  DISCONNECT: "disconnect",
};
